### ISSUE TITLE
Gap betwen section to far

### ISSUE THREAD

**Issue by kubil-ismail** [alkarim99/food-recipe-fe-react#1]
![Screenshot (105)](https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/e1ae7e99-90ed-4259-ac03-02edef3f0f5b)
![Screenshot (106)](https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/f01c2ddf-df0c-41fe-bc9a-ab85b2bd9603)

Fix this gap section, don't use height 100vh. If your content to short this gap will show and make your website ux bad, istad using height 100vh you can use margin bottom

**Comment by alkarim99** [comment]
![Screenshot (424)](https://github.com/alkarim99/food-recipe-fe-react/assets/76543950/7930f5b9-2f7e-4f67-b686-3078659b2bdc)
![Screenshot (425)](https://github.com/alkarim99/food-recipe-fe-react/assets/76543950/0a8a9167-8de6-4669-bd40-1fa661efe771)
I have fix this issue, please check, thanks🙏

**Comment by kubil-ismail** [comment]
done
<img width="1680" alt="Screenshot 2023-08-09 at 23 50 33" src="https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/81ae76f7-4bb7-4486-8799-6fcc76827564">
