### ISSUE TITLE
Fix your login/register screen

### ISSUE THREAD

**Issue by kubil-ismail** [alkarim99/food-recipe-fe-react#2]
![Screenshot (109)](https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/50b3ee79-3b30-4044-b8a3-360f1edea8fa)
![Screenshot (108)](https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/a49db7ae-a81d-465b-b6e0-7a881e4c934b)

Change overflow-x from auto to none in your parent root in this page. And make left content height to fullscreen in register page.

**Comment by alkarim99** [comment]
![Screenshot (426)](https://github.com/alkarim99/food-recipe-fe-react/assets/76543950/8ca18588-ad31-48b2-8438-b9ab434d52ae)
![Screenshot (427)](https://github.com/alkarim99/food-recipe-fe-react/assets/76543950/1983170e-9daf-4e48-8d1e-bfe2f9db201e)
I have fix this issue, please check, thanks🙏

**Comment by kubil-ismail** [comment]
the issue still not solved in macbook screen 16 inch for register page
<img width="1680" alt="Screenshot 2023-08-09 at 23 39 10" src="https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/10eb4703-45d7-46ae-b60a-8fb84eba6731">

**Comment by kubil-ismail** [comment]
the issue solved for login page
<img width="1680" alt="Screenshot 2023-08-09 at 23 45 14" src="https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/3cbd2443-36c6-4e49-96f7-24b88eaef788">

**Comment by alkarim99** [comment]
![image](https://github.com/alkarim99/food-recipe-fe-react/assets/76543950/49e84bb8-b60c-4314-b914-508c6b009676)
I have fix new issue on register page, please check, thanks🙏
