### ISSUE TITLE
Change placeholder if recipe not found

### ISSUE THREAD

**Issue by kubil-ismail** [alkarim99/food-recipe-fe-react#3]
![Screenshot (110)](https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/b887eef1-5ae4-4beb-9124-5f130a7db0e6)

If recipe not found just show alert bootstrap showing message _recipe not found please create your first recipe_

**Comment by alkarim99** [comment]
![Screenshot (428)](https://github.com/alkarim99/food-recipe-fe-react/assets/76543950/c49f9169-7384-4fc2-93e6-d60e0e579109)
![Screenshot (429)](https://github.com/alkarim99/food-recipe-fe-react/assets/76543950/a067d082-5c03-4204-b426-ea7ac66002cb)
I have fix this issue, please check, thanks🙏

**Comment by kubil-ismail** [comment]
Solved
<img width="1680" alt="Screenshot 2023-08-09 at 23 41 07" src="https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/333710cc-f644-4414-b31f-c1faed5ee946">

**Comment by kubil-ismail** [comment]
but got new issue on register page in macbook size 16 inch. please fix the layout
<img width="1680" alt="Screenshot 2023-08-09 at 23 39 10" src="https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/5fce1978-e015-440f-a093-da66284ad8d6">

**Comment by alkarim99** [comment]
![image](https://github.com/alkarim99/food-recipe-fe-react/assets/76543950/9207dc29-0857-41a2-b636-a752b57723e1)
I have fix new issue on register page, please check, thanks🙏
