### ISSUE TITLE
Fix video system

### ISSUE THREAD

**Issue by kubil-ismail** [alkarim99/food-recipe-fe-react#4]
![Screenshot (111)](https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/d10e36b4-1240-4a86-b9f6-7ff36f24748d)

Check if youtube link is not valid iframe just redirect to new tab and open url

**Comment by alkarim99** [comment]
![image](https://github.com/alkarim99/food-recipe-fe-react/assets/76543950/f0c21bdb-3702-4e6f-bb81-5644f14f440e)
I have fix this issue, please check, thanks🙏

**Comment by kubil-ismail** [comment]
video link successfully opened in new tab

<img width="1680" alt="Screenshot 2023-08-09 at 23 35 33" src="https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/7102dd18-eae0-4aef-aa4d-84f46e0f6e6b">

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-09 at 23 35 24" src="https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/2753b67c-da11-4033-a431-fa9b3cfd4c57">
