### ISSUE TITLE
Handle size in large desktop mode.

### ISSUE THREAD

**Issue by kubil-ismail** [alkarim99/food-recipe-fe-react#5]
![Screenshot (113)](https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/ca18add1-a395-44c7-accb-73ec985d91a1)

If check from laptop 13 & 14 inch, content show with no problem but in large destop 27 inch break your layout design. Please fix

**Comment by alkarim99** [comment]
![image](https://github.com/alkarim99/food-recipe-fe-react/assets/76543950/c2a66c24-df77-480e-be35-fe83705916b0)
I have fix this issue, please check, thanks🙏

**Comment by kubil-ismail** [comment]
<img width="1680" alt="Screenshot 2023-08-09 at 23 31 40" src="https://github.com/alkarim99/food-recipe-fe-react/assets/49361887/71c701de-5fa6-458c-b94c-a76b5de5dcd9">

layout design solved but the title "All Recipe" in the upper section. please fix it

**Comment by kubil-ismail** [comment]
the capture opened in 16 inch macbook

**Comment by alkarim99** [comment]
![image](https://github.com/alkarim99/food-recipe-fe-react/assets/76543950/4318e2ca-5013-4675-90c9-73728f4b86ee)
I have fix title "All Recipe" issue on home page, please check, thanks🙏
